log:
  level: INFO
  format: "json"

serversTransport:
  insecureSkipVerify: true

entryPoints:
  web:
    address: 0.0.0.0:80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  web2:
    address: 0.0.0.0:80
    http:
      redirections:
        entryPoint:
          to: websecure2
          scheme: https
  websecure:
    address: 0.0.0.0:443
    http:
      tls: {}
    http3: false
  websecure2:
    address: 0.0.0.0:443
    http:
      tls: {}
    http3: true

providers:
  file:
    filename: "/file.yaml"
